import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

/**
 * This is the home page
 * @return {JSX.Element}
 */
const Home: NextPage = (): JSX.Element => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Daniel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Home;
